### PR TITLE
Added Frameless Window support for macOS

### PR DESCRIPTION
**Pull request by duongdev**
I love [Electron's frameless apps on macOS](https://electron.atom.io/docs/api/frameless-window/) and I believe many people also do. So I added some lines of code to make the app looks better.
Hope you will love it.

image

### CODE REVIEW

**Comment by hex2f** [comment]
That actually looks really clean! Just make sure it's an option in settings :)

**Comment by tahnik** [comment]
I agree with @RekkyRek. Need to have a setting for this.

**Comment by duongdev** [comment]
@RekkyRek @tahnik frameless windows always better. So all of Electron frameless apps I know (Slack, GitKraken, Caprine, VSCode, ...) make their apps borderless by default.

I don't have any Windows machine to test this feature on Windows. Any guy can help?

**Comment by hex2f** [comment]
@duongdev Essentially no programs are borderless on windows or Linux.

Windows: you have to make your own close / minimize buttons which can confuse users as it does not look like all other programs.

Linux: There are a huge range of customization in the Linux world, therefore it's important not to mess with the topbar since it can be very confusing for the buttons to be in a different order or be on the wrong side of the window.

**Comment by smachave** [comment]
@duongdev VSCode and Slack aren't frameless on Windows at least. We would need to add the buttons manually for Linux and Windows (from what it looks like).
> There are two alternatives to choose between. Either remove the frame for all three platforms using frame: false when initializing the browserwindow in main.js. Or you can use titleBarStyle: ‘hidden’. This alternative is only for macOS.

**Comment by cozyplanes** [comment]
not recommended to change the title bar in windows/linux

**Comment by hex2f** [comment]
We could probably add this for Mac but we won't do windows and Linux I guess

**Comment by tahnik** [comment]
Closing this as we would soon drop active support for this project.

**Pull request closed without merging**
