### PR TITLE
Replaced the manual date formatting with "toLocaleDateString"

### LINKED ISSUE #252: Incorrect Date Displaying
https://devrant.io/rants/1175531

screen shot 2018-03-10 at 12 56 35 pm

### PR DESCRIPTION
**Pull request by cactysman**
This fixes a slight oversight of the fact that months are 0-based in JS Date functions.
The date formatting previously was done manually without adding `1` to the month integer.
Also instead of manually constructing the date string, it is now rendered using [Date.prototype.toLocaleDateString()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString).

Fixes #252

### CODE REVIEW

**Comment by cactyx** [comment]
I set the locale used for the new date format rendering to `en-GB` mainly because that's what the current date format seems to be. This may be omitted / selectable for the user if that should be a future feature.

**Review by mainrs — COMMENTED** [review]
Looks good, I'll wait till the tests pass.

**Review by mainrs — APPROVED** [review]
Approved

**Comment by cactyx** [comment]
Thank you.

**Pull request merged**
