### PR TITLE
Add support for newlines

### PR DESCRIPTION
**Pull request by jonasgeiler**
I finally added support for newlines on the profile in the about and skills section.
Hope it's okay if I do such a simple PR.

### CODE REVIEW

**Comment by jonasgeiler** [comment]
Also supports tabs btw.

**Comment by tahnik** [comment]
@Skayo thanks for the PR. Could you please add a screenshot of the bug? It looks like the newlines are working correctly without this in the profile section.

**Comment by jonasgeiler** [comment]
@tahnik Will do ASAP

**Comment by jonasgeiler** [comment]
@tahnik 
There you go:
Image

**Info:**
OS: Kali Linux 64 Bit - Version 2018.1
devRantron-Version: v1.5.3

**Pull request merged**
